build:
  build_target: vllm
  artifact_dir: shared
  torch_whl_dir: dist
  base_image: ${DOCKER_IMAGE}
  dockerfile_path: "./.github/docker/external/vllm/Dockerfile.base"
test:
  - label: Basic Correctness Test # 30min
    id: vllm_basic_correctness_test
    tests:
    - env_var: VLLM_WORKER_MULTIPROC_METHOD=spawn
      op: globle_env
    - command: pytest -v -s basic_correctness/test_cumem.py
    - command: pytest -v -s basic_correctness/test_basic_correctness.py
    - command: pytest -v -s basic_correctness/test_cpu_offload.py
    - command: pytest -v -s basic_correctness/test_preemption.py
      env_var: VLLM_TEST_ENABLE_ARTIFICIAL_PREEMPT=1
